name: Add submodule AdamRaichu/code
on:
  workflow_dispatch: 
jobs:
  npm:
    name: clone AdamRaichu/code
    runs-on: ubuntu-latest
    steps:
    - name: import GitHub actions checkout
      uses: actions/checkout@v3
    - name: run git
      run: |
        git submodule add -b ghpages-mirror-test https://github.com/AdamRaichu/code
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "push from clone.yml"
        git push
