name: Add submodule AdamRaichu/code
on:
  workflow_dispatch: 
    inputs:
      repo_url:
        description: 'url of the repo'
        default: "https://github.com/OWNER/REPO"
        required: true
      branch:
        description: "namespace of the branch to clone"
        default: "main"
        required: true
jobs:
  npm:
    name: clone AdamRaichu/code
    runs-on: ubuntu-latest
    steps:
    - name: import GitHub actions checkout
      uses: actions/checkout@v3
    - name: run git
      run: |
        git submodule add -b ${{ github.event.inputs.branch }} ${{ github.event.inputs.repo_url }}
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "push from clone.yml"
        git push
