name: Update a submodule
on:
  workflow_dispatch: 
    inputs:
      submodule_name:
        description: 'name of the submodule from .gitmodules'
        default: "code"
        required: true
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
    - name: import GitHub actions checkout
      uses: actions/checkout@v3
    - name: import Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: remove submodule
      run: |
        git rm ${{ github.event.inputs.submodule_name }}
    - uses: actions/github-script@v6
    - name: Get gitmodule object
      id: get-gitmodule
      run: |
        node update_yml.js
    - name: re-add submodule
      run: |
        git submodule add -b ${{ steps.get-gitmodule.outputs.MODULE_ONE_BRANCH }} ${{ steps.get-gitmodule.outputs.MODULE_ONE_URL }}
    - name: push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "used update.yml to update submodule ${{ github.event.inputs.submodule_name }}"
        git push
